genesis:
  chainID: 10000
  difficulty: "0x1"
  gasLimit: "0xe0000000"
  alloc:
    balance: "1000000000000000000000000000"

quorum:
  # Selection consensus mechanism: istanbul or raft
  consensus: raft
  # Docker container image
  image: quorumengineering/quorum:2.5.0
  # Logging verbosity: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail
  verbosity: 3
  # Listen port
  ports:
    raft: 50400
    rpc: 8545
    listen: 30303
  # Environment variables used to start the container
  env:
    - PRIVATE_CONFIG=ignore
