- name: "Get nodekey"
  shell:
    cmd: /usr/local/bin/generator
  register: result

- set_fact:
    private_key: "{{ result.stdout_lines[0][2:] }}"
    public_key: "{{ result.stdout_lines[1][2:] }}"

- when: private_key | length == 64 and public_key | length == 128
  debug:
    msg: "
        {{ private_key }}
        {{ public_key }}
    "
